pipeline {
    agent any
    
    tools {
        jdk "jdk17"
        maven "maven3"
    }
    
    environment{
        GIT_REPO = 'https://github.com/Khaled1771/TheUltimate-CI-CD.git'
        BRANCH = 'dev'
        
        IMAGE_NAME = 'osamaseyam/board-game'
        IMAGE_TAG = 'latest'
        SCANNER_HOME = tool 'sonar-scanner'
    }
    
    stages {
        stage('Git Checkout') {
            steps {
                git branch: "${BRANCH}", credentialsId: 'git-cred', url: "${GIT_REPO}"
            }
        }
        
        stage('Compile') {
            steps {
                script {
                    dir('BoardGame') {
                        sh 'mvn compile'
                    }
                }
            }
        }
        
        stage('Test') {
            steps {
                script {
                    dir('BoardGame') {
                        sh 'mvn test'
                    }
                }     
            }
        }
        
        stage('File System Scan') {
            steps {
                sh 'trivy fs --format json -o trivy-fs-report.json .'
            }
        }
        
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh '''
                       $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=BoardGame-dev -Dsonar.projectKey=BoardGame-dev \
                       -Dsonar.java.binaries=. 
                    '''
                }
            }
        }
            
        stage('Quality Gate') {
            steps {
                script{
                    waitForQualityGate abortPipeline: true
                }
            }
        }
        
        stage('Build'){
            steps{
                script {
                    dir('BoardGame') {
                        sh 'mvn package'
                    }
                }
            }
        }

        stage('Publish To Nexus') {
            steps {
                retry(3) {
                    script {
                        withMaven(globalMavenSettingsConfig: 'global-settings', jdk: 'jdk17', maven: 'maven3', mavenSettingsConfig: '', traceability: true) {
                            dir('BoardGame') {
                                sh 'mvn deploy'
                            }
                        }
                    }
                }
            }
        }
        
        stage('Build & Tag Docker Image'){
            steps{
                script { 
                    withDockerRegistry(credentialsId: "docker-cred", toolName:'docker'){
                        dir('BoardGame') {
                            sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."                        
                        }
                    }
                }
            }
        }
        
        stage('Docker Image Scan') {
            steps {
                sh "trivy image --format json -o trivy-image-report.json ${IMAGE_NAME}:${IMAGE_TAG}"
            }
        }
        
        
        stage('Push Docker Image'){
            steps{
                script { 
                    withDockerRegistry(credentialsId: "docker-cred", toolName:'docker'){
                        sh "docker push ${IMAGE_NAME}:${IMAGE_TAG}"
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline execution was successful.'
        }

        failure {
            echo 'Pipeline execution failed. Check the logs for more information.'
        }

        always {
             sh 'docker logout'

            script{
                def jobName = env.JOB_NAME
                def buildNumber = env.BUILD_NUMBER
                def pipelineStatus = currentBuild.result ?: "UNKNOWN"
                def bannerColor = pipelineStatus.toUpperCase() == 'SUCCESS' ? 'green' : 'red'
                
                def body = """
                    <html>
                        <body>
                            <div style="border: 4px solid ${bannerColor}; padding: 10px;">
                                <h2> ${jobName} - Build ${buildNumber} </h2>
                                <div style="background-color: ${bannerColor}; padding: 10px">
                                    <h3 style="color: white;"> Pipeline Status: ${pipelineStatus.toUpperCase()} </h3>
                                </div>
                                <p> Check the <a href="${BUILD_URL}"> console output. </a></p>
                            </div>
                        </body>
                    </html>
                """
                
                
                emailext(
                    subject: "${jobName} - Build ${buildNumber} - ${pipelineStatus.toUpperCase()}",
                    body: body,
                    to: 'osamamostafa065@gmail.com,abdelrahman.hamouda29@gmail.com',
                    from: "jenkins-BoardGame-CD-pipline@gmail.com",
                    replyTo: "jenkins-BoardGame-CD-pipline@gmail.com",
                    mimeType: 'text/html',
                    attachmentsPattern: 'trivy-image-report.json,trivy-fs-report.json'
                )
            }
        }
    }
}