controller:
  image:
    repository: osamaseyam/custom-jenkins
    tag: latest
    pullPolicy: IfNotPresent

  volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock

  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
