#######     Kubernetes play-book     ####### 
---

- name: Kubernetes Operations
  hosts: <target-host>
  remote_user: <used-user-on-vm>
  become: true
  tasks:

  - name: Apply Kubernetes Manifest to create the deployment
    shell: kubectl apply -f ../Kubernetes/Deployment.yml

  - name: Apply Kubernetes Manifest to create the LoadBalancer
    shell: kubectl apply -f ../Kubernetes/ingress.yml

